### ISSUE TITLE
Question | Any example for mentioning?

### ISSUE THREAD

**Issue by Moshikot3** [coolnickname/baileys-REST#6]
There is a example for mentioning group member?
I tried using mentionedJid in several scenarios, but I failed...

**Comment by coolnickname** [comment]
This repository is not supported and uses an outdated version of the Baileys library. I believe this version of Baileys did not support mentioning users, not sure if that feature has since been implemented.

Assuming this project still works, your best bet would be to use the [send raw message request](https://github.com/coolnickname/baileys-REST/blob/12683463fcc6e1121f628b055adecc092af78caa/server.js#L207), as I assume you've already done. You'll have to browse the Baileys source code to figure out which elements you need to fill in in your "message" object, however I think if this was possible with the version of Baileys I built this API on I would have documented it.
